resources:
- repo: self

trigger:
- master
- maint/*

jobs:
- job: documentation
  displayName: 'Generate Documentation'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      git config user.name 'Documentation Generation'
      git config user.email 'noreply@libgit2.org'
      docker run --rm -v /home/vsts/work/1/s:/src -w /src libgit2/docurium:test cm doc api.docurium
      git checkout gh-pages
      cp -R * '$(Build.BinariesDirectory)'
    displayName: 'Generate Documentation'
  - task: archivefiles@2
    displayName: 'Archive Documentation'
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/api-documentation.zip'
  - task: publishbuildartifacts@1
    displayName: 'Upload Documentation Artifact'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'docs'
  - script: git push origin gh-pages
    displayName: 'Publish Documentation'
    condition: eq(variables['Build.Reason'], 'IndividualCI')
